---
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y docker-ce

script:
  - docker build -t centos7 .
  - docker run -d --privileged --name centos centos7
  - docker exec --tty centos ansible --version
