---
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y docker-ce

script:
  - docker build -t centos6:latest .
  - docker run -d --privileged --name centos centos7:latest
  - docker exec --tty centos ansible --version

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag centos6:latest $DOCKER_USERNAME/docker-ansible:centos6-latest
  - docker push $DOCKER_USERNAME/docker-ansible:centos6-latest

branches:
  only:
    - centos7
    - centos6
  except:
    - /^testing-.*$/
    - master