---
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y docker-ce

script:
  - docker build -t centos7:latest .
  - docker run -d --privileged --name centos centos7:latest
  - docker exec --tty centos ansible --version

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag centos7:latest $DOCKER_USERNAME/docker-ansible:centos7-testing-latest
  - docker push $DOCKER_USERNAME/docker-ansible:centos7-testing-latest

branches:
  only:
    - /^centos7-.*$/
    - /^centos6-.*$/
  except:
    - /^testing-.*$/
    - master